config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:sessions]
  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: :new_admin_session
    post 'login', to: 'devise/sessions#create', as: :admin_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  post 'sms/receive'
  resources :users

  root 'home#index'
  get 'home/index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deployment.rb
class Deployment < ApplicationRecord
  def description
    "#{cause} - #{city}, #{country}"
  end
end

app/models/help.rb
class Help < Message

  TRIGGER_SMS_TEXT = 'help me'

  def response
    "Courier bot - Help \n - To request a need, send: \n need <description of your request> \n - To report an event, send: \n report <description of the event>"
  end


  def to_be_broadcasted?
    false
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  attr_accessor :text_errors

  def process!
    nil
  end

  def response
    ''
  end

  def to_be_broadcasted?
    true
  end

  def user_and_time_desc
    "#{user.name}, on #{received_at.strftime('%b %-d %Y, %-l:%M%p')} UTC"
  end
end

app/models/need.rb
class Need < Message

  STREAM_NAME = 'user_message_need'

  def process!
    save!
  end

  def response
    "Thanks, your need (##{id}) has been registered."
  end

end

app/models/report.rb
class Report < Message

  STREAM_NAME = 'user_message_report'

  def process!
    save!
  end

  def response
    "Thanks, your report (##{id}) has been registered."
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  validates :name, :phone_number, presence: true
  validate :phone_number_format

  def phone_number_format
    unless phone_number =~ /\A[+]\d{8,}\z/
      errors.add(:phone_number, 'is not valid.')
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user ||= User.new
  end

  def about
  end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def receive
    analyzer = Twilio::Analyzer.new(sms: params)
    analyzer.read_sms_and_create_message!
    analyzer.broadcast_message

    messenger = Twilio::Messenger.new(analyzer: analyzer)
    messenger.send
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{@user.name} (#{@user.phone_number}) has been registered."
      redirect_to root_path
    else
      render 'home/index'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "#{@user.name}'s profile has been deleted."
    else
      flash[:alert] = "An error ocurred, please try again later."
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%section#intro
  %p Courier bot is a simple chatbot demo. Its aim is to enable people on the frontline to send text messages for quick and easy reporting to admins.

  %div#instructions
    To get started:
    %ul
      %li= "As a admin, register the user who will be texting (their name and phone number):"
      %li.simple-user-form
        = simple_form_for @user, method: :post, html: {class: 'form-inline'} do |f|
          = f.input :name, label: 'Name: ', class: 'form-control mb-2 mr-sm-2'
          = f.input :phone_number, label: 'Phone number: ', placeholder: 'eg. +12223334444', class: 'form-control mb-2 mr-sm-2'
          = f.button :submit, 'Create user', id: 'submit-new-user', class: 'btn btn-primary'
      %li Then as a user, text 'help me' to +15799771147 to see available commands.
      %li Start sending text messages (commands) to that same number. They'll be showing up in the "Needs &amp; Reports" list underneath automatically.

%section#needsReports
  %h4 Needs &amp; Reports
  .container
    .row
      .col
        %table.table#needTable
          %thead
            %tr
              %th.col Needs
          %tbody
            - Need.order(id: :desc).limit(10).each do |need|
              = render 'shared/list_item', message: need

      .col
        %table.table#reportTable
          %thead
            %tr
              %th.col Reports
          %tbody
            - Report.order(id: :desc).limit(10).each do |report|
              = render 'shared/list_item', message: report

%hr

%section#lastWords
  %p= "Once you're done, go to the #{ link_to "User page", users_url } to delete the profile you created. Also, find out more #{ link_to "about Courier Bot and the idea behind this project", '#', data: {toggle: 'modal', target: '#aboutModal'} }.".html_safe

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %title Courierbot
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navigation'

    .container#mainContent
      - if notice.present?
        .alert.alert-success.alert-dismissable.fade.show{role: 'alert'}
          = notice
          %button{type: 'button', class: 'close', 'data-dismiss': 'alert', 'aria-label': 'Close'}
            %span{'aria-hidden': 'true'} &times;
      - if alert.present?
        .alert.alert-danger.alert-dismissable.fade.show{role: 'alert'}
          = alert
          %button{type: 'button', class: 'close', 'data-dismiss': 'alert', 'aria-label': 'Close'}
            %span{'aria-hidden': 'true'} &times;

      = yield
    = render 'shared/about_modal'

app/views/shared/_about_modal.html.haml
#aboutModal.modal.fade{"aria-hidden": "true", "aria-labelledby": "aboutModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#aboutModalLabel.modal-title About Courier Bot
        %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
          %span{"aria-hidden": "true"} ×
      .modal-body
        %p= "Courier Bot is a simple SMS reporting proof-of-concept. This application is the result of observations made by reading about projects used in humanitarian aid and disaster relief over the past years (projects such as #{ link_to 'FrontlineSMS', 'https://www.frontlinesms.com/', target: '_blank'}, #{ link_to 'Ushahidi', 'https://www.ushahidi.com/', target: '_blank'}, #{ link_to 'Needslist', 'https://needslist.co/', target: '_blank'}...).".html_safe

        %p= "Courier Bot is for demo-purpose only. Its source code can be found #{ link_to 'on Github', 'https://github.com/etiennebaque/courierbot', target: '_blank' }.".html_safe

        %p= "This project was built using Rails 5. It's using the #{ link_to 'TwilioSMS', 'https://www.twilio.com/', target: '_blank'} API and websockets through Rails 5 #{ link_to 'ActionCable', 'https://guides.rubyonrails.org/action_cable_overview.html', target: '_blank'}. It also uses Devise for authentication, Bootstrap 4, and Redis.".html_safe

        %p= "If you have any questions or feedback, please feel free to send me an email at #{ link_to 'mail@etiennebaque.com', 'mailto:mail@etiennebaque.com' }.".html_safe

        %p= "Thanks for giving Courier Bot a try! :-)"
      .modal-footer
        %button.btn.btn-primary{"data-dismiss": "modal", type: "button"} Close

app/views/shared/_list_item.html.haml
%tr
  %td
    = message.description
    %span.reporter= "(#{message.user_and_time_desc})"

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to 'Courier Bot demo', root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    - if admin_signed_in?
      %ul.navbar-nav
        %li.nav-item
          = link_to 'Users', users_path, class: 'nav-link'
        %li.nav-item
          = link_to 'About', '#', class: 'nav-link', data: {toggle: 'modal', target: '#aboutModal'}

      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'nav-link'

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/index.html.haml
.back-link
  = link_to "< Back to home page", root_url

%section#user-list
  %h3 Users

  - if @users.present?
    %table.table.table-striped
      %thead
        %tr
          %th{scope: 'col'}
            Name
          %th{scope: 'col'}
            Phone number
          %th{scope: 'col'}
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.phone_number
            %td= link_to "Delete user", user, method: :delete, data: {confirm: "Are you sure?"}

  - else
    There is no registered user at the moment.

%section#new-user
  %h4 Create a new user

  .container
    .row
      .col-12.col-md-6
        = simple_form_for(User.new) do |f|
          = f.input :name, label: 'Name', error: 'The name is mandatory, please specify one'
          = f.input :phone_number, placeholder: 'eg. +12223334444'
          = f.button :submit, id: 'submit-new-user', class: 'btn btn-primary'

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml